nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

npmScopes:
  broker:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmRegistryServer: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmAuthToken: ${REGISTRY_TOKEN}
  tradingview:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmRegistryServer: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmAuthToken: ${REGISTRY_TOKEN}
  encapital:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmRegistryServer: "https://packages.entrade.com.vn/artifactory/api/npm/encapitalnpm-local/"
    npmAuthToken: ${REGISTRY_TOKEN}